[project]
name = "lilacs-vts-tracker"
requires-python = ">= 3.9"
requires-python = "< 3.13"
description = "Plugin for VTube Studio for camera-based face tracking with mediapipe."

[tool.black]
line-length = 79
